bno055_node:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "i2c"
    i2c_bus: 1                   # Jetson TX2 Pin 27/28 (Bus 1)
    i2c_addr: 40                 # 0x28 hex = 40 dec
    data_query_frequency: 50.0   # 50Hz dong bo voi chu ky UDP Gateway
    calib_status_frequency: 0.1  # 0.1Hz = 10s kiem tra calib 1 lan
    frame_id: "imu_link"
    operation_mode: 12           # 12 = 0x0C = NDOF mode
    placement_axis_remap: "P0"

    # Scale factors chuan
    acc_factor: 100.0
    mag_factor: 16000000.0
    gyr_factor: 900.0
    grav_factor: 100.0

    # Offsets ban dau dat false de calib
    set_offsets: false
    offset_acc: [0, 0, 0]
    offset_mag: [0, 0, 0]
    offset_gyr: [0, 0, 0]
    radius_acc: 1000
    radius_mag: 680

bno055:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "i2c"
    i2c_bus: 1
    i2c_addr: 40
    data_query_frequency: 50.0
    calib_status_frequency: 0.1
    frame_id: "imu_link"
    operation_mode: 12
    placement_axis_remap: "P0"

    acc_factor: 100.0
    mag_factor: 16000000.0
    gyr_factor: 900.0
    grav_factor: 100.0

    set_offsets: false
    offset_acc: [0, 0, 0]
    offset_mag: [0, 0, 0]
    offset_gyr: [0, 0, 0]
    radius_acc: 1000
    radius_mag: 680